branch-defaults:
  default:
    environment: choose-a-share-aws
environment-defaults:
  choose-a-share-aws:
    branch: null
    repository: null
global:
  application_name: choose-a-share-aws
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
